title: Share Your Chatgpt Chat
description: Community-contributed ChatGPT conversations
baseurl: "/ChatSharing" # Sửa lại thành "/ChatSharing", không có dấu cách
url: "https://yasir13001.github.io/ChatSharing"
permalink: /:categories/:year/:month/:day/:title.html
markdown: kramdown
theme: minima
